SELECT REL.REE_NORE, NSE.NSE_NUMS, NSE.ART_CODE
FROM REL_DAT REL
JOIN NSE_DAT NSE ON NSE.ART_CODE = REL.ART_CODE 
    AND REL.REL_NoSU = NSE.STK_NoSU
WHERE REL.ACT_CODE = 'RB'
    AND NSE.NSE_NUMS = 'RO6962962338'
	--AND NSE.ART_CODE = 'VC249298000-1'